apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-service
  annotations: {}
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "fratschi.20.71.73.61.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-service
            port:
              number: 8080
