apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 1
  values:
    loki:
      persistence:
        enabled: true
      replicas: 1
      serviceMonitor:
        enabled: true
        additionallLabels:
        - release: monitoring
      ingress:
        enabled: false
        hosts:
        - host: "loki.home.krizic.net"
          paths:
          - "/"
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
        additionallLabels:
        - release: monitoring
