apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  chart:
    spec:
      chart: influxdb
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 1
  values:
    image:
      tag: latest
    nodeSelector:
      kubernetes.io/arch: arm64
    ingress:
      enabled: true
      hostname: influxdb.home.krizic.net
    user:
      username: "admin"
      password: "influx"
