apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: false
        prometheusInstance: kube-prometheus-stack
        labels:
          release: kube-prometheus-stack
